### ISSUE TITLE
关于代码运行报错

### ISSUE THREAD

**Issue by yanqiangmiffy** [hyliush/ccks-2021-task2-baseline#5]
您好，请问下fastNLP用的什么版本，
```

 dev_label_list = dev_out['infer_labels']
 dev_raw_char = datasets[dataset_name]['raw_chars']  # 原始文字

```
这两个字段都是拿不到的

**Comment by hyliush** [comment]
不好意思，要改一下，pipeline.py的304行，我写的是pred，提交的时候和task3搞混了，把后面的改一下吧

Send from Liu Hengyuan

在 2021年7月7日，11:04，yanqiangmiffy ***@***.***> 写道：

﻿

您好，请问下fastNLP用的什么版本，


 dev_label_list = dev_out['infer_labels']
 dev_raw_char = datasets[dataset_name]['raw_chars']  # 原始文字



这两个字段都是拿不到的

**Comment by hyliush** [comment]
rawchars拿不到吗，如果拿不到，应该很早就会报错了，因为loaddata里用到了这个字段

Send from Liu Hengyuan

在 2021年7月7日，11:04，yanqiangmiffy ***@***.***> 写道：

﻿

您好，请问下fastNLP用的什么版本，


 dev_label_list = dev_out['infer_labels']
 dev_raw_char = datasets[dataset_name]['raw_chars']  # 原始文字



这两个字段都是拿不到的

**Comment by yanqiangmiffy** [comment]
dev_label_list = dev_out['pred']
dev_raw_char = datasets[dataset_name]['chars']  # 原始文字
dev_raw_label = datasets[dataset_name]['target']  # 标签

原始代码改成这样才可以

**Comment by yanqiangmiffy** [comment]
但是有一个比较奇怪的地方是，代码跑完之后，只能预测4条，后来检查了下，pipeline的Tester中的predict方法代码稍微有点问题，这一行缩进有问题
https://github.com/hyliush/ccks-2021-task2-baseline/blob/9c093f193c7e2d33481aea2693a89ed6f50fa58c/pipeline.py#L300
，应该放在while循环里面，否则只能返回最后一batch数据。


改了上面错误之后，
https://github.com/hyliush/ccks-2021-task2-baseline/blob/9c093f193c7e2d33481aea2693a89ed6f50fa58c/pipeline.py#L301
这一行拼接有错误，
```
  inference_labels = np.concatenate(inference_labels, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 23 and the array at index 1 has size 31
```
检查了下是应该是长度没有对齐感觉。

所以如果一开始
```
 dev_label_list = dev_out['infer_labels']
 dev_raw_char = datasets[dataset_name]['raw_chars']  # 原始文字
```
这两个字段你代码能运行的话，应该是fastNLP框架版本有问题，构建的datasets属性都不一样了，我这里用的fastNLP=0.6.0,构建datasets属性是
```
dev_raw_char = datasets[dataset_name]['chars'] # 原始文字
dev_raw_label = datasets[dataset_name]['target'] # 标签
```
所以想确认下你的fastNLP版本是多少？
